version: '3'
networks:
  id-wall:

services:
  app:
    build: .
    networks:
      - id-wall
    hostname: idw.app
    container_name: idw_app
    platform: linux
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: postgres:10.3
    restart: always
    networks:
      - id-wall
    hostname: idw.db
    container_name: ge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  adminer:
    image: adminer
    networks:
      - id-wall
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres: